/**
 * Created by wzhan039 on 2015-07-15.
 * value in array to easy search
 */
var mimes = {'hqx':['application/mac-binhex40'],
    'cpt':['application/mac-compactpro'],
    'csv':['text/x-comma-separated-values', 'text/comma-separated-values', 'application/octet-stream', 'application/vnd.ms-excel', 'application/x-csv', 'text/x-csv', 'text/csv', 'application/csv', 'application/excel', 'application/vnd.msexcel'],
    'bin':['application/macbinary'],
    'dms':['application/octet-stream'],
    'lha':['application/octet-stream'],
    'lzh':['application/octet-stream'],
    'exe':['application/octet-stream', 'application/x-msdownload'],
    'class':['application/octet-stream'],
    'psd':['application/x-photoshop'],
    'so':['application/octet-stream'],
    'sea':['application/octet-stream'],
    'dll':['application/octet-stream'],
    'oda':['application/oda'],
    'pdf':['application/pdf'],
    'ai':['application/postscript'],
    'eps':['application/postscript'],
    'ps':['application/postscript'],
    'smi':['application/smil'],
    'smil':['application/smil'],
    'mif':['application/vnd.mif'],
    'doc':['application/msword'],
    'docx':['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'],
    'xls':['application/excel', 'application/vnd.ms-excel', 'application/msexcel'],
    'xlsx':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    'ppt':['application/powerpoint', 'application/vnd.ms-powerpoint'],
    'pptx':['application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    'wbxml':['application/wbxml'],
    'wmlc':['application/wmlc'],
    'dcr':['application/x-director'],
    'dir':['application/x-director'],
    'dxr':['application/x-director'],
    'dvi':['application/x-dvi'],
    'gtar':['application/x-gtar'],
    'gz':['application/x-gzip'],
    'php':['application/x-httpd-php'],
    'php4':['application/x-httpd-php'],
    'php3':['application/x-httpd-php'],
    'phtml':['application/x-httpd-php'],
    'phps':['application/x-httpd-php-source'],
    'js':['application/x-javascript'],
    'swf':['application/x-shockwave-flash'],
    'sit':['application/x-stuffit'],
    'tar':['application/x-tar'],
	'rar':['application/x-rar-compressed'],
    'tgz':['application/x-compressed'],
    '7z':['application/x-7z-compressed'],
    'xhtml':['application/xhtml+xml'],
    'xht':['application/xhtml+xml'],
    'zip':  ['application/x-zip', 'application/zip', 'application/x-zip-compressed'],
    'mid':['audio/midi'],
    'midi':['audio/midi'],
    'mpga':['audio/mpeg'],
    'mp2':['audio/mpeg'],
    'mp3':['audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'],
    'aif':['audio/x-aiff'],
    'aiff':['audio/x-aiff'],
    'aifc':['audio/x-aiff'],
    'ram':['audio/x-pn-realaudio'],
    'rm':['audio/x-pn-realaudio'],
    'rpm':['audio/x-pn-realaudio-plugin'],
    'ra':['audio/x-realaudio'],
    'rv':['video/vnd.rn-realvideo'],
    'wav':['audio/x-wav', 'audio/wave', 'audio/wav'],
    'bmp':['image/bmp', 'image/x-windows-bmp'],
    'gif':['image/gif'],
    'jpeg':['image/jpg', 'image/jpe', 'image/jpeg', 'image/pjpeg'],
    'jpg':['image/jpg', 'image/jpe', 'image/jpeg', 'image/pjpeg'],
    'jpe':['image/jpg', 'image/jpe', 'image/jpeg', 'image/pjpeg'],
    'png':['image/png',  'image/x-png'],
    'tiff':['image/tiff'],
    'tif':['image/tiff'],
    'css':['text/css'],
    'html':['text/html'],
    'htm':['text/html'],
    'shtml':['text/html'],
    'txt':['text/plain'],
    'text':['text/plain'],
    'log':['text/plain', 'text/x-log'],
    'rtx':['text/richtext'],
    'rtf':['text/rtf'],
    'xml':['text/xml'],
    'xsl':['text/xml'],
    'mpeg':['video/mpeg'],
    'mpg':['video/mpeg'],
    'mpe':['video/mpeg'],
    'qt':['video/quicktime'],
    'mov':['video/quicktime'],
    'avi':['video/x-msvideo'],
    'movie':['video/x-sgi-movie'],
    //'xlsx':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'],
    'word':['application/msword', 'application/octet-stream'],
    //'xls':['application/excel'],
    'eml':['message/rfc822'],
    'json' : ['application/json', 'text/json'],
    'msg':['application/vnd.ms-outlook','text/plain'],
    'tc':['text/html','text/plain']
    };
var validSuffix={octer:['so','dll','bin','exe'],
                        ps:['psd'],
                        pdf:['pdf'],
                        text:['csv','txt','log','xml','html','css','js','json'],
                        msdoc:['doc','docx'],
                        msexcel:['xls','xlsx'],
                        msppt:['ppt','pptx'],
                        msoutlook:['msg'],
                        compress:['tar','tgz','gz','zip','rar','7z'],
                        image:['jpg','jpeg','png','gif','bmp'],
                        video:['avi','rm','wav','swf','mpeg','moive','mp4','rmvb']
}
exports.mimes=mimes;
exports.validSuffix=validSuffix;

